### ISSUE TITLE
3.0preview2

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1099]
8月末に出せないかな。→9月序盤に

issue
- [ ] #1032 標準のPDFを印刷に寄せる →#1033, #1072 でだいたい解決してる？
- [x] #1073 /samples移動→#1100 で対応
- [ ] #1090 calcLayout→ #1076 を入れる or geometryを仮復帰
- [ ] #1093 ライセンス明記化 → 大変なのでRe:VIEW MTGで決めようかな

PR
- [x] #1098 review-epub2html
- [x] #890 chapref,column gettext
- [x] #1100 /samples移動
- [ ] #1105 review-initにアップロード機能。pre2で入れてみたい…

**Comment by takahashim** [comment]
8月末は詰んでそう（そもそも東京にいない）ので9/2でどうですか…？

**Comment by kmuto** [comment]
はい、10月正式リリース目標であと2回ベータを入れていけばいいかなと思っているだけですので、9/2で問題ないです。
そもそも使ってるヒトがすごく少なそう……

**Comment by kmuto** [comment]
こちらいかがでしょう？＞@takahashim

**Comment by takahashim** [comment]
おっとすみません、１日遅れましたがこちらリリースしておきます

**Comment by takahashim** [comment]
リリースしました https://rubygems.org/gems/review/versions/3.0.0.preview2

**Comment by kmuto** [comment]
あ、#1076 はよかったんでしょうか

**Comment by takahashim** [comment]
#1076 はどうせpreviewで確定ではないのでということで突っ込んでもよかったかもですが、meetingで出た話を踏まえてでもよいかと思いました

**Comment by kmuto** [comment]
りょうかいです。ではいろいろアナウンスしていきますかね。
