### ISSUE TITLE
3.0 preview3

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1107]
10月頭。というか10/16までには…

PRマージしたいもの

- [x] #812 PR #1105 review-initダウンロード機能
- [x] #1032 PR #1117 標準のPDFを印刷に寄せる新しいjsbookとjlreq。 #1076 は使わない。#912 #1090 #1064 #1115 も波及修正される。#1129 通しノンブルもセットで修正される。#1131 隠しノンブルもセットで修正される
- [x] #1136 PR #1140 gentombowをvendorに入れるかどうか( #1117 ブランチ派生)
- [x] #1093 PR #1112 ライセンス明記化（#1140 を入れたら修正）
- [x] #868 PR #1138 imgmathロジックの改良（マージしたらconfig.yml.sampleを書く）
- [x] PR #1137 NEWSファイル。（上記をマージしていったら★の箇所を消す）

済み

- [x] #1128 PR #1130  \frontmatterをtitlepageの前へ 
- [x] PR #1118 Rubocop追従

post preview3

- [ ] #1110 POSTDEFでの図表に限らず\frontmatter/\backmatterでのchapterでfigure/tableのカウンタがリセットされない

**Comment by kmuto** [comment]
よろしゅー m(__)m

**Comment by takahashim** [comment]
https://github.com/kmuto/review/releases/tag/v3.0.0.preview3
https://rubygems.org/gems/review/versions/3.0.0.preview3
リリースしました

**Comment by kmuto** [comment]
ありがとうございます！！
