### ISSUE TITLE
3.0.0 preview4

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1149]
pre3のあとにリリース。
RCまたはそのまま3.0とするもの

入れたい

- [ ] PR #1169 リリースノート。★を消していく
- [x] #1147 PR #1148 review-jlreqにもhiddenfolio実装
- [x] #1160 PR #1162 idgxml/plain/textbuilderにおいて`@<chapref>`の挙動をほかのビルダに合わせる
- [x] #1156 PR #1159 syntax-book, sample-bookに対してこれまでどおりrake pdfが正しく動くように修正
- [x] #1146 PR #1165  imgmathがtexequationで効かない?→fontsizeをtexequation内にも記載することで回避
- [x] #1144 PR #1164 既存のプロジェクトの更新方法（post 3.0releaseでもいい） 2から3への支援が早速必要そう。
- [x] #1167 PR #1168 texequationの採番

以下は次で対処に。

- [ ] #1142 PR #1153 dir+"/foo"とかのFile.join化
- [ ] #1151 PR #1166  文字サイズをQではなくptで指定したい。行高もmmやscaleで指定したい →単位付き指定が可能なfontsize,baselineskipは入れた。frontedgeとtailはまだ動いていないがどうしよう。あとQではなくJQ値に変換しているのが正しいことかどうか出力で比較したほうがよさそう。
- [ ] #1152 無効化したクラスオプションの扱い、見出しサイズのjsbook準拠戻し
- [ ] #1155 review-jsbookで無効化したクラスオプションの扱い。clsファイルにさらに手入れが必要→PR #1164 のreview-updateで記法移行自体はできる
- [ ] #1110 PREDEFやPOSTDEFでの図表の採番リセット(TeXの歴史的仕様のようだが実際困る)
- [ ] #1158 tombopaper=を指定するとhiddenfolioが無視される

**Comment by kmuto** [comment]
はい、ありがとうございます！

**Comment by kmuto** [comment]
リリースエンジニアリング、ありがとうございました。
