### ISSUE TITLE
3.0.0 RC or release

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1174]
3.0.0 RCまたは正式リリースのための作業

入れたい

- [x] #1186 リリースノート。★を消していく
- [x] #1171 PR #1173 review-jsbookでpaperwidth,paperheightが効かない
- [x] #1142 PR #1153 dir+"/foo"とかのFile.join化
- [x] #1151 PR #1200  文字サイズをQではなくptで指定したい。行高もmmやscaleで指定したい →単位付き指定が可能なfontsize,baselineskipは入れた。frontedgeとtailはまだ動いていないがどうしよう。あとQではなくJQ値に変換しているのが正しいことかどうか出力で比較したほうがよさそう。
- [x] #1158 PR #1176  tombopaper=を指定するとhiddenfolioが無視される
- [x] PR #1177 どうしてもjsbook.clsを使い続けたい向きのためにreview-base.styに最低限の互換性対処を施す 
- [x] PR #1175 review-jsbookにclearonepage, clearoddpageを追加
- [x] #1152 PR #1200 見出しサイズのjsbook準拠戻し
- [x] PR #1182 TeX: review-jlreqにoneblankpageとclearoddpageマクロを追加 
- [x] #1183 PR #1184 review-updateでstyフォルダがうまく更新されない
- [x] #1181 PR #1185 TeX:mediaクラスオプションを導入（camerareadyの別名）
- [x] #1195 PR #1196 TeX: part内での下位見出しを許容する
- [x] PR #1189 doc: quickstartにreview-updateについての記載  
- [x] PR #1188 doc: idgxmlの情報を更新
- [x] PR #1190 doc: config.yml.sample を更新
- [x] PR #1191 doc: pdfmakerの情報を更新 
- [x] PR #1201 review-updateのfontsize対応。#1200 待ち
- [x] PR #1202 review-initでtexdocumentclassを明示指定。#1200 待ち
- [x] PR #1203 review-jsbook READMEの更新 #1200 待ち
- [x] PR #1204 review-jlreq のREADME更新
- [x] #1206 PR #1207 (新機能になってしまうが、)表列が段落モードになっているときには表セル分割を\newlineにする
- [x] PR #1208 TeXにL,C,Rのセルスタイルを追加。明示的にtsizeで指定しない限り使わないので問題ないはず…
- [x] #1210 PR #1211 TLのバージョン差異での挙動エラーを避けるため、jsbook.clsとgentombow.styをvendorに持っておいてコピーする

できれば手当てしたい

- [x] #1187 ドキュメント更新
- #1152 #1155 無効化したクラスオプションの扱い →どうしてもjsbookがいいという人は #1177 でもよいような
- #1110 PREDEFやPOSTDEFでの図表の採番リセット(TeXの歴史的仕様のようだが実際困る)。jlreqのほうはクラス側で対処される見込み

**Comment by takahashim** [comment]
https://github.com/kmuto/review/releases/tag/v3.0.0.rc1 にてリリースしました。
