### ISSUE TITLE
Re:VIEW 3.1

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1230]
- [x] PR #1229 samples内のgentombowスタイルファイルの名前を修正
- [x] #1231 PR #1232 HTMLBuilder: emlistnum, listnumもhighlightメソッドを必ず経由するようにする
- [x] #1233 PR #1234 EPUBで脚注から「戻る」リンクおよび脚注記号のカスタマイズ
- [x] #1235 PR #1237 TeX: review-jsbookでnumber_of_linesの数が指定より1行減ってしまうのを修正
- [x] PR #1240 TeX: \makelinesマクロの追加
- [x] PR #1239 README.mdのjsbook.clsについてのファイル名ミスを修正
- [x] #1243 PR #1244 review-jlreqでupLaTeX固有になっていた箇所をLuaLaTeXでも動作するよう修正
- [x] #1247 PR #1248 `#@mapfile`などでre拡張子が指定された場合はタブなどを変形させずそのまま取り込む
- [ ] #1241 media=previewを入れる？
- [x] #1242 Ruby 2.6をtravisビルド対象に追加
- [x] #1250 TeX: review-jlreqで単位にzwを使っている部分を\zwに置き換え。およびコラムに字下げを追加
- [x] #1252 PR #1253 TeX: 奥付で左列が長いときにあふれるのを修正
- [x] #1254 PR #1255 TeX: 図版キャプション向けに\reviewimagecaptionを導入。2系は\captionのままにしているので互換性は崩れないが、3系はreview-updateの実行が必要

**Comment by kmuto** [comment]
ありがとうございましたー＞ @takahashim
