### ISSUE TITLE
Re:VIEW 4.1リリース

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#1411]
2020年2月を予定

Issues
- [ ] #1397 review-jlreqでのjlreqtrimmarkssetupの利用
- [ ] #1393 IDにスペースほかビルダにまずいものをエラーか警告にする。まずはIndexBuilder待ち
- [ ] #1320 キャプションの上・下の設定
- [x] #1163 cls,styにバージョン追加 #1413 
- [x] #1414 後方互換性処理でエラー #1415 
- [x] #1416 review-jlreq+lualatexでエラー #1417 
- [ ] #1421 ビルダごとの画像オプション →ドキュメントに書く？記法ちょっと考える？
- [x] #1423 セル区切りの任意指定 
- [x] #1432 tt/codeを見出しで使いmedia=ebookだとエラー

PR
- [ ] #1384 IndexBuilder WIPで実装待ち
- [ ] #1361 issue #1320の対応。いちおうできているけど汚い？
- [x] #1412 Dockerfile更新
- [x] #1413 バージョン情報追加
- [x] #1415 issue #1414の修正
- [x] #1417 #1416 review-jlreq+LuaLaTeXでのエラーを修正
- [x] #1424 RuboCop 0.77.0対応
- [x] #1425 config.yml.sampleに奥付の連絡先および順序についてのコメントを追加
- [x] #1427 IDGXMLBuilder: 表IDの引き渡しのやり方を修正
- [x] #1428 IDGXMLMakerに-yオプションを追加し、特定ファイルのみをビルドできるように
- [x] #1429 IDGXMLMakerのフィルタプログラムがエラーになったときにクラッシュするのを修正
- [x] #1423 add table_split_regexp parameter
- [x] #1422 needs one more compile when makeindex is true
- [x] #1426 update rstbuilder.rb by @turky 
- [x] #1430 fix ERB.new arguments
- [x] #1431 use GitHub Actions
- [x] #1434 #1432 の対応。ひとまずrevertする
- [x] #1435 #1432 の正式な対応。#1434は不要になる。
- [x] #1433 PDFを実際に作ってみて確認するようにする

**Comment by kmuto** [comment]
2月29日ってもろ技術書典とかぶったんですが、リリース作業は @takahashim さんの状況的にどうなんでしょう…

#1415 があるのでできればあまり遅くなりたくないところ。今のところマージ済みの範囲のものはマイナーアップデートで互換性の変化はないです。

**Comment by takahashim** [comment]
まあ事前に準備できていれば何とかなるのでは…？！

**Comment by takahashim** [comment]
というわけでリリースしました https://rubygems.org/gems/review/versions/4.1.0

**Comment by kmuto** [comment]
ありがとうございます!!
